### ISSUE TITLE
begging for a demo of training FV dictionary

### ISSUE THREAD

**Issue by zhuqiang00099** [avagait/pfmgait#3]
Dear @mjmarin ,I have been paying attention to your research for a period of time. I am a chinease Master graduate student who is new in gait recognition. I think that I can learn a lot from your research including papers and code. Now ,I want to completely running your pipeline include how to train the data, but the code is just based on the trained FV dictionary. May it be a easy work for someone familiar with this kind of tasks, but hard for a green hand like me.If you have time,could you provide a simple demo for me.Thank you for reading such a long message.

**Comment by fmcp** [comment]
Hi @zhuqiang00099, 

thanks for your interest. Right now I don't have too much time to create a complete demo for training. By the end of the next week I will have some time so I will create a basic demo.

Meanwhile, you can check the file [https://github.com/avagait/pfmgait/blob/master/code/Gait/mj_trainGaitGen.m](url) which performs the whole training process.

**Comment by zhuqiang00099** [comment]
@fmcp Thanks for your quick reply.Your research helps me a lot, and next I will learn your paper and code.Thanks for your reply again,sincerely.
