### ISSUE TITLE
some questions of implementation details

### ISSUE THREAD

**Issue by zhuqiang00099** [avagait/pfmgait#4]
@fmcp  I am sorry, but after two weeks, I have another problem. Thanks for your last reminder, according to your code, I completed the training part. Then, after testing some datasets, I think the training code is basically correct, but I still have some details to ask you.

1. Pyramidal representation
    If I want to get a two-level pyramid that one level is a full body and another level contains two cells, should I train totally three dictionaries?Does each column feature contain three sections(because of 3 cells).

2. People detection
   The 'demodetect' uses GMM to detect people, but your paper (Fisher Motion Descriptor
for Multiview Gait Recognition 2016) uses specialized people detectors. Since the datasets have the static background, GMM is accurate enough and fast. How about people detectors? If possible,can you provide the code?

3. About Last request
   I'm not in a hurry to need a complete example now. Of course, it would be best if you provided a complete example if you were free. And, I just need the code for 'Fisher Motion Descriptor
for Multiview Gait Recognition', not all papers.

Thanks again!

**Comment by fmcp** [comment]
Hi,

sorry for the late answer. I uploaded a .mat file with the parameters of the partitions used in the paper. The rest of the code should use those parameters without problems. A dictionary per partition must be trained.

Regarding the detection, I uploaded a demo using a detector. Note that you must install the library voc-release4.01.

**Comment by zhuqiang00099** [comment]
OK,thanks a lot. @fmcp 
During these days, I have been written some training code based on yours, and tested on the CASIA-B dataset，a ha! Anyway, your paper and code helps me a lot, thank you!
